# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Reinhart
email: benjreinhart@gmail.com
description: Personal page of Ben Reinhart, software developer.
baseurl: ""
url: http://benreinhart.com
twitter_username: benjreinhart
github_username:  benjreinhart

# Build settings
markdown: kramdown

kramdown:
  input: GFM
