title: Ben Reinhart
author: Ben Reinhart
description: >-
  Personal website and blog of Ben Reinhart
keywords:
  - ben reinhart
  - website
  - blog
  - software
  - software developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benreinhart.com"

twitter_link: "https://twitter.com/benjreinhart"
github_link: "https://github.com/benjreinhart"
linkedin_link: "https://www.linkedin.com/in/bereinhart"
email_link: "mailto:benjreinhart@gmail.com"

blog:
  date_format: "%B %-d, %Y"

exclude:
  - cli
  - README.md
  - notes.md
